const FIELDWORK_API_HOST = 'api.dofieldwork.com'
const FIELDWORK_API_PROTOCOL = 'http'
const FIELDWORK_API_VERSION = 'v1'
const FIELDWORK_API_BASE_URL = `${FIELDWORK_API_PROTOCOL}://${FIELDWORK_API_HOST}/api/${FIELDWORK_API_VERSION}/projects`

export default {
  FIELDWORK_API_BASE_URL,
}
